### ISSUE TITLE
License of the Asset?

### ISSUE THREAD

**Issue by Okabintaro** [geegaz/GClimbingSystem#1]
Hey there! Thanks for putting this system out. I tried it out and its working really well.
You didn't include a license, so I it's a bit unclear if it's fine to use the asset in a published world.

Can you include a license of the asset? See https://choosealicense.com/no-permission/ for more information about it.
Most other assets like for example the contact system from Vowgan uses the MIT License(https://github.com/VirtualVisions/VowganPrefabs/blob/master/Contact/LICENSE.md).

Thanks!

**Comment by geegaz** [comment]
Glad you enjoyed this asset and thanks for the reminder !
It's intended to be licensed under MIT, I just added the licence file to the repository.
